/*
 * File: app/store/TestTypesStore.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('LanistaTrainer.store.TestTypesStore', {
    extend: 'Ext.data.Store',

    requires: [
        'LanistaTrainer.model.TestTypes',
        'Ext.data.proxy.Ajax',
        'Ext.data.reader.Json'
    ],

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            model: 'LanistaTrainer.model.TestTypes',
            storeId: 'TestTypesStore',
            proxy: {
                type: 'ajax',
                url: '/tpmanager/user/testtypesjson',
                reader: {
                    type: 'json'
                }
            }
        }, cfg)]);
    }
});