/*
 * File: app/view/PlanEditPanel.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('LanistaTrainer.view.PlanEditPanel', {
    extend: 'Ext.form.Panel',
    alias: 'widget.planEditPanel',

    requires: [
        'Ext.form.field.TextArea'
    ],

    height: 250,
    id: 'planEditPanel',
    width: 400,
    bodyPadding: 10,
    title: 'My Form',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'textfield',
                    fieldLabel: 'Label',
                    name: 'name'
                },
                {
                    xtype: 'textfield',
                    fieldLabel: 'Label',
                    name: 'duration'
                },
                {
                    xtype: 'textareafield',
                    fieldLabel: 'Label',
                    name: 'description'
                }
            ],
            listeners: {
                afterrender: {
                    fn: me.onPlanEditPanelAfterRender,
                    scope: me
                }
            }
        });

        me.callParent(arguments);
    },

    onPlanEditPanelAfterRender: function(component, eOpts) {
        this.down( 'field[name=name]' ).setLabel( Ext.ux.LanguageManager.TranslationArray.FORM_PLAN_NAME );
        this.down( 'field[name=duration]' ).setLabel( Ext.ux.LanguageManager.TranslationArray.FORM_PLAN_TIME );

        this.down('field[name=name]').on('change', function(component) {
            LanistaTrainer.app.fireEvent('showSavePanel', 'savePlanDataButton', 'cancelPlanDataButton');
        });
        this.down('field[name=duration]').on('change', function(component) {
            LanistaTrainer.app.fireEvent('showSavePanel', 'savePlanDataButton', 'cancelPlanDataButton');
        });
    }

});