/*
 * File: app/model/Customer.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('LanistaTrainer.model.Customer', {
    extend: 'Ext.data.Model',

    requires: [
        'Ext.data.field.Integer',
        'Ext.data.field.String',
        'Ext.data.field.Date',
        'Ext.data.field.Boolean'
    ],

    fields: [
        {
            type: 'int',
            name: 'id'
        },
        {
            type: 'string',
            name: 'first_name'
        },
        {
            type: 'string',
            name: 'last_name'
        },
        {
            type: 'string',
            name: 'email'
        },
        {
            type: 'string',
            name: 'street'
        },
        {
            type: 'string',
            name: 'city'
        },
        {
            type: 'string',
            name: 'zipcode'
        },
        {
            type: 'string',
            name: 'country'
        },
        {
            type: 'string',
            name: 'note'
        },
        {
            type: 'string',
            name: 'phone_nr'
        },
        {
            type: 'string',
            name: 'birthday'
        },
        {
            type: 'int',
            name: 'gender'
        },
        {
            name: 'deleted'
        },
        {
            name: 'image'
        },
        {
            type: 'date',
            name: 'last_change'
        },
        {
            name: 'language'
        },
        {
            type: 'boolean',
            defaultValue: false,
            name: 'synchronized'
        }
    ]
});