/*
 * File: app/model/TestResults.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('LanistaTrainer.model.TestResults', {
    extend: 'Ext.data.Model',

    requires: [
        'Ext.data.Field'
    ],

    fields: [
        {
            name: 'trainer_id',
            type: 'string'
        },
        {
            name: 'test_results',
            type: 'string'
        },
        {
            name: 'test_comments',
            type: 'string'
        },
        {
            name: 'testtype',
            type: 'string'
        },
        {
            name: 'customer_id',
            type: 'string'
        },
        {
            name: 'test_date',
            type: 'string'
        }
    ]
});