/*
 * File: app/controller/ToolsController.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('LanistaTrainer.controller.ToolsController', {
    extend: 'Ext.app.Controller',

    id: 'languagesController',

    control: {
        "viewport #toolsButton": {
            click: 'onToolsButtonClick'
        }
    },

    onToolsButtonClick: function(button, e, eOpts) {

        button.menu.alignTo(button, 'c-c',[100,0]);

    },

    onShowTools: function(tool) {
        //if (tool == 'MUSCLES')

        //if (tool == 'SKELETON')

        if (tool == 'STOP_WATCH')
            LanistaTrainer.app.fireEvent('showStopWatch');

    },

    init: function(application) {
        application.on({
            showTools: {
                fn: this.onShowTools,
                scope: this
            }
        });
    }

});
